[env:native]
platform = native
test_framework = unity
test_build_src = yes

build_flags =
    -std=c++11

    ; Warnings
    -Wall
    -Wextra
    -Wpedantic
    -Werror
    -Wshadow
    -Wconversion
    -Wsign-conversion
    -Wformat=2
    -Wundef
    -Wnull-dereference
    -Wdouble-promotion

    ; Better analysis/debuggability
    -O1
    -g3
    -fno-omit-frame-pointer

    ; Runtime checks
    -fsanitize=address,undefined
    -fno-sanitize-recover=all
    -D_GLIBCXX_ASSERTIONS

    ; Project includes
    -DUNITY_INCLUDE_DETAILS
    -Ihal
    -Itest

check_tool = clangtidy
check_flags =
    --format-style=google
    --config-file=.clang-tidy
check_src_filters =
    +<src/**>
    +<include/**>
    +<hal/**>