[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_flags =
    -std=c++11
    -Wall    # Enable all warnings to catch potential issues (Rule 10 from the power of 10)
    -Werror  # Treat warnings as errors to enforce code quality
    -g
    -DUNITY_INCLUDE_DETAILS
    -Ihal
    -Itest
check_tool = clangtidy
check_flags = --format-style=google --config-file=.clang-tidy
check_src_filters =
    +<src/**>
    +<include/**>
    +<hal/**>
