#ifndef DATA_NAMES_H
#define DATA_NAMES_H
// Defines the uint8_t value for each data stream

// Sensor data
#define CURE_ACCELEROMETER_X 0
#define CURE_ACCELEROMETER_Y 1
#define CURE_ACCELEROMETER_Z 2
#define CURE_GYROSCOPE_X 3
#define CURE_GYROSCOPE_Y 4
#define CURE_GYROSCOPE_Z 5
#define CURE_TEMPERATURE 6
#define CURE_PRESSURE 7
#define CURE_ALTITUDE 8
#define CURE_MAGNETOMETER_X 9
#define CURE_MAGNETOMETER_Y 10
#define CURE_MAGNETOMETER_Z 11

// Metrics
#define CURE_MEDIAN_ACCELERATION_SQUARED 12
#define CURE_AVERAGE_CYCLE_RATE 13
#define CURE_NUM_PACKETS_SENT 24

// Metadata
#define CURE_TIMESTAMP 14
#define CURE_STATE_CHANGE 15
#define CURE_CURRENT_STATE 23
#define CURE_FLIGHT_ID 16

// State Estimation
#define CURE_EST_APOGEE 17
#define CURE_EST_VERTICAL_VELOCITY 18
#define CURE_EST_ALTITUDE 19
#define CURE_TIME_TO_APOGEE 22
#define CURE_ROLL 25
#define CURE_PITCH 26
#define CURE_YAW 27

// Power
#define CURE_BATTERY_VOLTAGE 20

// Active Aero
#define CURE_FIN_DEPLOYMENT_AMOUNT 21

// Payload
#define CURE_PROBE_TEMPERATURE 28

#endif
