name: Clang-Tidy Check

on:
  #triggers the workflow on pull requests
  pull_request:
    branches:
      - '**'

  #allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  clang-tidy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Avionics repo
        uses: actions/checkout@v4

      - name: Install PlatformIO Core
        run: |
          pip install -U platformio

      - name: Run Clang-Tidy Check
        run: pio check -e native --fail-on-defect=low --fail-on-defect=medium --fail-on-defect=high

