name: Unit Tests

on:
  #triggers the workflow on pull requests
  pull_request:
    branches:
      - '**'

  #allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  test-native:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Avionics repo
        uses: actions/checkout@v4

      - name: Download Rocket-test-data v1.0.0 release CSVs
        run: |
          mkdir -p data
          curl -s \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/CURocketEngineering/Rocket-Test-Data/releases/tags/v1.0.0 \
          | jq -r '.assets[].browser_download_url' \
          | while read url; do
              echo "Downloading $url"
              curl -L "$url" -o data/$(basename "$url")
            done

      # Fixes the file name replacing the dots with spaces
      - name: Fix file name
        run: |
          mv data/AA.Data.Collection.-.Second.Launch.Trimmed.csv \
             data/"AA Data Collection - Second Launch Trimmed.csv"

      - name: Install PlatformIO Core
        run: |
          pip install -U platformio

      - name: Run PlatformIO Tests
        run: pio test -e native

